import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

/*
  Generated class for the TagsProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class TagsProvider {

    metatags = { "Coiffure" : ["Coupe Femme",
                    "Coloration",
                    "Coloration Racine",
                    "Balayage",
                    "Mèches",
                    "Tie & Dye",
                    "Ombré Hair",
                    "Shampoing",
                    "Lissage",
                    "Lissage brésilien",
                    "Brushing",
                    "Permanente",
                    "Défrisage",
                    "Tissage",
                    "Afro",
                    "Beauté",
                    "Esthétique",
                    "Chignon",
                    "Minceur",
                    "Soin du cheveu",
                    "Coupe Homme",
                    "Barbe Homme"],
              "Ongles" : [  "Manucure",
                    "Pédicure",
                    "French Manucure",
                    "French Pedicure",
                    "Vernis semi-permanent",
                    "Vernis permanent",
                    "Ongles en gel",
                    "Nail art",
                    "Réparation ongle cassé",
                    "Extension/Faux ongles",
                    "Faux ongles Résine",
                    "Remplissage d'ongles",
                    "Traitement paraffine"],
              "Massage" : [	"4 ou 6 mains",
                    "Aux pierres chaudes",
                    "Acupression",
                    "Pré/Post natal",
                    "Amincissant",
                    "Mains",
                    "Pieds",
                    "Pierre de lave",
                    "Indien (de la tête)",
                    "Aux compresses d'herbes",
                    "Thérapeutique",
                    "Sportif",
                    "Visage",
                    "Suédois",
                    "Ayurvédique",
                    "En couple",
                    "Thailandais",
                    "Réflexologie",
                    "Chinois",
                    "Aux huiles essentielles",
                    "Dos, épaules et cou",
                    "Deep tissue",
                    "Californien",
                    "Shiatsu"],
             "Epilation" : ["Maillot",
                    "Maillot intégral",
                    "Maillot brésilien",
                    "Maillot américain",
                    "Jambes",
                    "Aisselles",
                    "Demis-bras",
                    "Bras entier",
                    "Demis-Jambes",
                    "Jambes entières",
                    "Dos",
                    "Ventre",
                    "Fesses",
                    "Visage",
                    "Visage (au fil)",
                    "Sourcil au fil",
                    "Lèvres au fil",
                    "Menton au fil",
                    "Joues au fil",
                    " Cou au fil",
                    "A la cire",
                    "Orientale",
                    "Lumière pulsée"],
            "Visage" : ["Extension de cils",
                    "Permanente de cils",
                    "Rehaussement de cils",
                    "Teinture des cils et des sourcils",
                    "Soin du visage micro-aiguilles",
                    "Soin du visage anti-acné",
                    "Épilation des sourcils au fil",
                    "Épilation des sourcils à la cire",
                    "Maquillage",
                    "Soin acupuncture rajeunissement",
                    "Soin du visage homme",
                    "Lifting visage non chirurgical",
                    "Peeling du visage",
                    "Thérapie lumineuse LED",
                    "Soin du visage peaux jeunes",
                    "Maquillage permanent et semi-permanent",
                    "Microblading",
                    "Soin des cils et sourcils",
                    "Microdermabrasion",
                    "Soin du visage femme",
                    "Soin du visage à l'oxygène",
                    "Consultation de la peau",
                    "Maquillage Jour",
                    "Maquillage Soirée",
                    "Maquillage Mariage"]
            };

  constructor(public http: HttpClient) {
    console.log('Hello TagsProvider Provider');
  }

}
